### ISSUE TITLE
Text Color

### ISSUE THREAD

**Issue by ozankonur** [edsilfer/sticky-index#12]
text color is not working. 

  <br.com.stickyindex.StickyIndex
        android:id="@+id/sticky_index_container_filter_by_league"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:textColor="#FFFFFF"
        android:layout_marginTop="@dimen/dp72"
        android:rowHeight="@dimen/dp7" />

**Comment by edsilfer** [comment]
Fixed in version `1.3.0` - see README.md to see how to obtain that.

```
<br.com.stickyindex.view.StickyIndex
            android:id="@+id/stickyIndex"
            android:layout_width="80dp"
            android:layout_height="wrap_content"
            android:textSize="20sp"
            android:textStyle="bold"
            app:rowHeight="64dp"
            app:stickyWidth="60dp"
            android:textColor="#0236e0"/>
```
<img width="134" alt="screen shot 2018-04-01 at 14 13 37" src="https://user-images.githubusercontent.com/12755321/38173005-e8350c5a-35b6-11e8-8f81-b531406254a3.png">
