### ISSUE TITLE
Versions conflicts with support library

### ISSUE THREAD

**Issue by Nams29** [edsilfer/sticky-index#15]
I have trouble importing the library in my project. It seems that there are conflicts between some support libraries versions and I can't find a way to fix it. I tried switching to version 27.0.2 but it didn't change anything even after a clean build.

```gradle
implementation "com.android.support:appcompat-v7:27.1.0"
implementation "com.android.support:support-v4:27.1.0"
implementation "com.android.support:design:27.1.0"
implementation "com.android.support:recyclerview-v7:27.1.0"

implementation 'com.github.edsilfer:sticky-index:1.3.0'
```

Error message : 
> All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.0, 27.0.2. Examples include com.android.support:recyclerview-v7:27.1.0 and com.android.support:animated-vector-drawable:27.0.2

Tools versions :
Android Studio 3.0.1
Gradle Tools 3.0.1

**Comment by amilham** [comment]
You can get around it by excluding `com.android.support` from the implementation. Change the line to:

```
implementation('com.github.edsilfer:sticky-index:1.3.0') {
        exclude group: 'com.android.support'
    }
```

**Comment by Nams29** [comment]
This solves the version conflict problem, but I get an other error when building : 

> Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> > java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

**Comment by edsilfer** [comment]
@Nams29 this is nothing to do with the library. Please, refer to stackflow questions like [this one](https://stackoverflow.com/questions/47079113/android-studio-3-0-execution-failed-for-task-unable-to-merge-dex).

**Comment by Nams29** [comment]
I tracked down the conflicts and excluded the group that was causing the problem : 

```
implementation('com.github.edsilfer:sticky-index:1.3.0') {
        exclude group: 'com.android.support'
        exclude group: 'android.arch.lifecycle'
    }
```

Still, it seems suspicious that the library would not import in a clean new project. I have nothing else that could cause this problem. 

Here is the project if you want to check : http://www.mediafire.com/file/t1v1vg59vzk08g5/MyApplication.zip.
