### ISSUE TITLE
import br.com.stickyindex.sample.databinding.ContactsViewBinding

### ISSUE THREAD

**Issue by amigax** [edsilfer/sticky-index#18]
#cannot import br.com.stickyindex.sample.databinding.ContactsViewBinding. Gave up in the end this seems to be the hardest lib ive ever tried to integrate. Mostly due to kotlin hell.

**Comment by edsilfer** [comment]
I would like to understand the reason why you are trying to import `br.com.stickyindex.sample.databinding.ContactsViewBinding`. This class is part of the sample project , it is not shipped in the library artifact, not being able to import it is expected. This library is does not provide a "contact app" interface, it provides sticky-index and fast scroller features. Could you please read through the `README` one more time.

Close as invalid

**Comment by amigax** [comment]
I was trying to integrate the sample app so I could use your contact selector, which looked good.

**Comment by edsilfer** [comment]
What do you mean by "contact selector"? The artifact that you import in your project by following the README instructions will only contain the files inside the `library` directory. Anything outside it will not be accessible when you add this library as dependency. If you see something in the `demo` app that you want, you should copy the file.
