### ISSUE TITLE
Can't use sticky-index with JCenter

### ISSUE THREAD

**Issue by Isolus** [edsilfer/sticky-index#5]
Adding sticky-index to a project causes the error 'Failed to resolve'. It seems related to the fact, that the project is named `sticky-index` and the metadata file refers to the name `stickyindex`.

**Comment by edsilfer** [comment]
It is true indeed, I'll try to fix this problem once I get out the work. Please use it from maven instead untill the issue is fixed. Thank you for noticing me about it.

**Comment by edsilfer** [comment]
Currently removing support for JCenter. If anyone hit this thread, please use `jitpack.io`
