### ISSUE TITLE
Failed to resolve: com.github.edsilfer:sticky-index:1.2.1

### ISSUE THREAD

**Issue by nvhaiwork** [edsilfer/sticky-index#7]
Hello,
I just update Android studio today(Gradle to 2.8), after update I cant resolve sticky-index any more.
This is error from Android studio:
`Failed to resolve: com.github.edsilfer:sticky-index:1.2.1`

**Comment by edsilfer** [comment]
Which API are you using? Is there a more complete stacktrace?

**Comment by jamez14** [comment]
Using Gradle 4.3 and API 27 and receiving the same error. Neither jcenter or maven is working (following the README install instructions)
