### ISSUE TITLE
min sdk version is 23

### ISSUE THREAD

**Issue by gilgil28** [edsilfer/sticky-index#8]
Is there any particular good reason?
You might want to change it to as low as posible.

**Comment by edsilfer** [comment]
No, no reason at all. I will change it by the end of this week. thanks for reminding me

**Comment by NageswaraRaoCH** [comment]
Still it is required min sdk version is 23.Any problem to changing???

**Comment by edsilfer** [comment]
@NageswaraRaoCH currently mim version is 15, however I haven't upload the package on JCenter. You can use [jitpack.io](https://jitpack.io/) to get the lates version or wait for me to release a new version of the lib - probably until the end of the week.

**Comment by Slinf** [comment]
Hi, i try compile my gradle and i have error cause of min version. 
> Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 22 declared
Can you downgrade minimal version?
